/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/KCGtFC9d9Dg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function MyHomePage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-background border-b px-4 lg:px-6 h-14 flex items-center">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Shop
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Categories
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
        <div className="ml-6 flex items-center gap-2">
          <Button size="icon" variant="ghost" className="rounded-full">
            <UserIcon className="h-5 w-5" />
            <span className="sr-only">Account</span>
          </Button>
          <Button size="icon" variant="ghost" className="rounded-full">
            <ShoppingCartIcon className="h-5 w-5" />
            <span className="sr-only">Cart</span>
          </Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6 grid md:grid-cols-2 gap-8 items-center">
            <div>
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Find the perfect products for you</h1>
              <p className="mt-4 max-w-[600px] text-muted-foreground md:text-xl">
                Explore our wide range of high-quality products and find the ones that suit your needs.
              </p>
            </div>
            <div>
              <Card className="overflow-hidden">
                <CardHeader className="flex flex-row items-center">
                  <div className="flex items-center space-x-4">
                    <Avatar>
                      <AvatarImage src="/placeholder-user.jpg" alt="Image" />
                      <AvatarFallback>OM</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="text-sm font-medium leading-none">Acme Support</p>
                      <p className="text-sm text-muted-foreground">support@acme.com</p>
                    </div>
                  </div>
                  <Button size="icon" variant="outline" className="ml-auto rounded-full">
                    <PlusIcon className="w-4 h-4" />
                    <span className="sr-only">New message</span>
                  </Button>
                </CardHeader>
                <CardContent>
                  <div className="space-y-4">
                    <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm ml-auto bg-primary text-primary-foreground">
                      Hi, how can I help you today?
                    </div>
                    <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm bg-muted">
                      I am looking for a new laptop, do you have any recommendations?
                    </div>
                    <div className="flex w-max max-w-[75%] flex-col gap-2 rounded-lg px-3 py-2 text-sm ml-auto bg-primary text-primary-foreground">
                      Absolutely, let me suggest a few options that might fit your needs.
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <form className="flex items-center w-full space-x-2">
                    <Input id="message" placeholder="" className="flex-1" autoComplete="off" />
                    <Button type="submit" size="icon">
                      <SendIcon className="w-4 h-4" />
                      <span className="sr-only">Send</span>
                    </Button>
                  </form>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Featured Products</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Discover our top picks</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Browse our curated selection of high-quality products that are sure to impress.
                </p>
              </div>
            </div>
            <div className="mx-auto grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 py-12">
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="300"
                    height="200"
                    alt="Product Image"
                    className="rounded-t-lg object-cover w-full aspect-[3/2]"
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-semibold">Wireless Headphones</h3>
                  <p className="text-muted-foreground text-sm">
                    Experience immersive sound with our premium wireless headphones.
                  </p>
                  <div className="flex items-center justify-between mt-4">
                    <span className="text-lg font-semibold">$99.99</span>
                    <Button size="sm">Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="300"
                    height="200"
                    alt="Product Image"
                    className="rounded-t-lg object-cover w-full aspect-[3/2]"
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-semibold">Smart TV</h3>
                  <p className="text-muted-foreground text-sm">
                    Upgrade your entertainment experience with our state-of-the-art smart TV.
                  </p>
                  <div className="flex items-center justify-between mt-4">
                    <span className="text-lg font-semibold">$499.99</span>
                    <Button size="sm">Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="300"
                    height="200"
                    alt="Product Image"
                    className="rounded-t-lg object-cover w-full aspect-[3/2]"
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-semibold">Fitness Tracker</h3>
                  <p className="text-muted-foreground text-sm">
                    Stay on top of your fitness goals with our advanced fitness tracker.
                  </p>
                  <div className="flex items-center justify-between mt-4">
                    <span className="text-lg font-semibold">$79.99</span>
                    <Button size="sm">Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="300"
                    height="200"
                    alt="Product Image"
                    className="rounded-t-lg object-cover w-full aspect-[3/2]"
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-semibold">Espresso Machine</h3>
                  <p className="text-muted-foreground text-sm">
                    Brew barista-quality espresso at home with our premium espresso machine.
                  </p>
                  <div className="flex items-center justify-between mt-4">
                    <span className="text-lg font-semibold">$199.99</span>
                    <Button size="sm">Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Recommended for You</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Products You Might Love</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Based on your browsing history and preferences, we have curated a selection of products that might
                  interest you.
                </p>
              </div>
            </div>
            <div className="mx-auto grid sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 py-12">
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="300"
                    height="200"
                    alt="Product Image"
                    className="rounded-t-lg object-cover w-full aspect-[3/2]"
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-semibold">Noise-Cancelling Headphones</h3>
                  <p className="text-muted-foreground text-sm">
                    Immerse yourself in your music with our top-of-the-line noise-cancelling headphones.
                  </p>
                  <div className="flex items-center justify-between mt-4">
                    <span className="text-lg font-semibold">$149.99</span>
                    <Button size="sm">Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="300"
                    height="200"
                    alt="Product Image"
                    className="rounded-t-lg object-cover w-full aspect-[3/2]"
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-semibold">Robotic Vacuum Cleaner</h3>
                  <p className="text-muted-foreground text-sm">
                    Effortlessly keep your floors clean with our advanced robotic vacuum cleaner.
                  </p>
                  <div className="flex items-center justify-between mt-4">
                    <span className="text-lg font-semibold">$299.99</span>
                    <Button size="sm">Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="300"
                    height="200"
                    alt="Product Image"
                    className="rounded-t-lg object-cover w-full aspect-[3/2]"
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-semibold">Cordless Power Drill</h3>
                  <p className="text-muted-foreground text-sm">
                    Tackle all your DIY projects with ease using our high-performance cordless power drill.
                  </p>
                  <div className="flex items-center justify-between mt-4">
                    <span className="text-lg font-semibold">$89.99</span>
                    <Button size="sm">Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    src="/placeholder.svg"
                    width="300"
                    height="200"
                    alt="Product Image"
                    className="rounded-t-lg object-cover w-full aspect-[3/2]"
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-lg font-semibold">Smart Home Hub</h3>
                  <p className="text-muted-foreground text-sm">
                    Centralize control of your smart home devices with our intuitive smart home hub.
                  </p>
                  <div className="flex items-center justify-between mt-4">
                    <span className="text-lg font-semibold">$99.99</span>
                    <Button size="sm">Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted p-6 md:py-12 w-full">
        <div className="container max-w-7xl grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-8 text-sm">
          <div className="grid gap-1">
            <h3 className="font-semibold">Company</h3>
            <Link href="#" prefetch={false}>
              About Us
            </Link>
            <Link href="#" prefetch={false}>
              Our Team
            </Link>
            <Link href="#" prefetch={false}>
              Careers
            </Link>
            <Link href="#" prefetch={false}>
              News
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Products</h3>
            <Link href="#" prefetch={false}>
              Men
            </Link>
            <Link href="#" prefetch={false}>
              Women
            </Link>
            <Link href="#" prefetch={false}>
              Kids
            </Link>
            <Link href="#" prefetch={false}>
              Accessories
            </Link>
          </div>
          <div className="grid gap-1">
            <h3 className="font-semibold">Resources</h3>
            <Link href="#" prefetch={false}>
              Blog
            </Link>
            <Link href="#" prefetch={false}>
              Community
            </Link>
            <Link href="#" prefetch={false} />
          </div>
        </div>
      </footer>
    </div>
  )
}

function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}


function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}





